AddToContent "<ul>"
AddToContent    "<li>Include plugins and files in frosoco_dev/frosoco_dev.</li>"
AddToContent	"<li>Change to production mode by changing steal.js"
AddToContent        " to steal.production.js in this file.</li>"
AddToContent "</ul>"